# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu666

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'auto-conn'
    subscriptionId: '640f9a55-4647-41fa-9e4e-19e2fbf98228'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ricky666'
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/outofthewoods1988/provisionAzureResource/blob/main/template.json'
    deploymentMode: 'Incremental'